### ISSUE TITLE
Consider changing engine property in package.json

### ISSUE THREAD

**Issue by sudodoki** [maxogden/github-oauth#7]
Is there any particular reason to have 0.8.x in package.json? That way you won't have to see some warning like:

    npm WARN engine github-oauth@0.0.4: wanted: {"node":"v0.8.x"} (current: {"node":"v0.10.XX"

**Comment by JamesMGreene** [comment]
@maxogden: The `engine` property has been removed from the "package.json" manifest, so this issue can be closed.

**Comment by sudodoki** [comment]
Fixed via https://github.com/maxogden/github-oauth/commit/f044e3ba0ad07bf121ae9c9211741f7212d18467.
